@startuml
'https://plantuml.com/sequence-diagram

autonumber

GameBoard -> Player: Create
GameBoard -> Apple: Create
Player -> Apple: Collect
Player -> Player: Increase score
Apple -> Apple: Create new


@enduml