@startuml

class GameBoard
{
    int size;
}

class Player
{
    int x;
    int y;
    int score;
}

class Apple
{
    int x;
    int y;

    NewApple();
}

GameBoard -> Player: Print
GameBoard -> Apple: Print
Player -> Apple: Collect

@enduml